name: delete branch on close of automerge PR
on: 
  pull_request:
    types: 
      - closed
  
jobs:
  delete-branch:
    if: ${{ github.event.label.name == 'automerge' }}
    runs-on: ubuntu-latest
    steps:
      - name: delete branch
        uses: SvanBoxel/delete-merged-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: remove labels
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: |
            automerge