name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: 19.0.3
          extra_plugins: |
            @semantic-release/changelog@6.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create PR
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: 'docs(CHANGELOG): update changelog [skip ci]'
          add-paths: |
            CHANGELOG.md
          delete-branch: true
          signoff: false
          draft: false
          labels: |
            automerge
            automated

